### ISSUE TITLE
Where is the Heroku 22 stack? Is the buildpacks project abandoned?

### ISSUE THREAD

**Issue by collimarco** [buildpacks/community#195]
There is no Heroku 22 buildpack... to my surprise the last one is Heroku 20 (`heroku/buildpacks:20`):

https://hub.docker.com/r/heroku/buildpacks/tags

Is there any explanation for this? When the `heroku/buildpacks:22` will be available?

**Comment by edmorley** [comment]
Hi!

The description in the overview for https://hub.docker.com/r/heroku/buildpacks says:

> See [heroku/builder](https://github.com/heroku/builder) for more information.

Visiting that repo there is a table of builder tags, with the Heroku-22 based images listed (now under `heroku/builder:*` and `heroku/builder-classic:*`):
https://github.com/heroku/builder#heroku-builder-images

I'll filed an internal issue for updating the repo description on Docker Hub to make the new location of later images clearer.

It's worth noting too, that `buildpacks/community` (where this issue is filed) is about the upstream buildpacks.io project, not Heroku buildpacks. For Heroku-specific buildpack issues, I would recommend using the Heroku repositories (such as https://github.com/heroku/builder or the various CNBs themselves).

**Comment by jjbustamante** [comment]
@hone , @samj1912 I think this issue can be closed.

**Comment by collimarco** [comment]
@edmorley Thank you very much for the clarification! We can close this issue.
